syntax = "proto3";

package plm.freecad;


message PlmFile {
  string id = 1;
  string name = 12;
  string fileName = 2;
  string label = 3;
  string lastModifiedBy = 4;
  string lastModifiedDate = 5;
  string comment = 6;
  string company = 7;
  string createdBy = 8;
  string createdDate = 9;
  repeated string externalLink = 10;
  bytes fileContent = 11;
  int64 cTimeNs = 13;
  int64 uTimeNs = 14;
  string sha1hex = 15;
  bytes filePreview = 16;
}

message PlmLink {
  enum LinkCopyOnChangeEnum {
    Disabled = 0;
    Enabled = 1;
    Owned = 2;
  }
  string linkedObject = 1;
  bool linkClaimChild = 2;
  bool linkTransform = 3;
  LinkCopyOnChangeEnum linkCopyOnChange = 4;
  double scale = 5;
  string plmFile = 6;
}

enum ServerStatus {
  OK_PROTO = 0;
  NOK_PROTO = 1;
  OK_FILES = 2;
  NOK_FILES = 3;
}

message Bucket {
  map<string, PlmFile> plmFiles = 1;
  map<string, PlmLink> links = 2;
  repeated string serverSha1Files = 3;
  ServerStatus status = 4;
}

// protoc-29.6-linux-x86_64/bin/protoc --python_out=/home/auo/tmp/py --java_out=/home/auo/tmp/java app/plm/src/main/proto/freecad_plm.proto